DROP TABLE IF EXISTS records;
DROP TABLE IF EXISTS categories;

CREATE TABLE categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(64) NOT NULL,
    color char(7) NOT NULL,
    is_income boolean DEFAULT false
);

CREATE TABLE records (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    description text DEFAULT '',
    category_id integer REFERENCES categories (id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
    amount money NOT NULL COLLATE "ru",
    date date NOT NULL
);